on:
  push:
    branches:
      - main
      - master

jobs:
  meu-job:
    runs-on: ubuntu-latest

    steps:
      - run: echo "💫 Esse job foi executado automaticamente por um evento"
      - run: echo "💯 Job está rodando em um servidor hospedado pelo GitHub!"

meu-segundo-job:   
    steps: 
      - run: echo "🌤 Informe o clima de amanhã em Goiânia. curl -s "wttr.in/?format=3"
      - run: echo "\t Informe que horas são agora."