on:
  push:
    branches:
      - main
      - master

jobs:
  meu-job:
    runs-on: ubuntu-latest

    steps:
      - run: echo "💫 Esse job foi executado automaticamente por um evento"
      - run: echo "💯 Job está rodando em um servidor hospedado pelo GitHub!"

  meu-segundo-job:   
    runs-on: ubuntu-latest

    steps: 
      - run:
             echo "🌤 Informe o clima de amanhã em Goiânia."
             echo ⌚ Informe que horas são agora. $(date +"%d/%m/%Y %H:%M:%S")
             ls -la
      - uses: actions/checkout@v6
      - run: ls -la