name: "[Automatica] Minha Primeira Action Linda!"

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs: 
      teste:
        description: "Meu primeiro input"
        required: true
        type: "string"
        
jobs:
  meu-job:
    runs-on: ubuntu-latest

    steps:
      - run: echo "💫 Esse job foi executado automaticamente por um evento"
      - run: echo "💯 Job está rodando em um servidor hospedado pelo GitHub!"

  meu-segundo-job:   
    runs-on: ubuntu-latest

    steps: 
      - name: Primeiro Step
        run: |
          echo "🌤 Informe o clima de amanhã em Goiânia."
          echo "⌚ Informe que horas são agora. $(date +'%d/%m/%Y %H:%M:%S')"
          echo "Hoje é $(TZ='America/Sao_Paulo' date +'%d/%m/%Y %H:%M:%S')"
          echo "Meu repositório se chama: ${{ github.repository }}"
          ls -la
      - name: Git checkout (faz o clone do repo)
        uses: actions/checkout@v6
      - name: "Verifica se o repo foi baixado"
        run: ls -la
